"""create links table

Revision ID: a3ee5cf893bb
Revises: 
Create Date: 2023-12-16 06:00:56.155178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3ee5cf893bb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link",
        sa.Column("path", sa.String(length=64), nullable=False),
        sa.Column("link", sa.String(length=2048), nullable=False),
        sa.PrimaryKeyConstraint("path"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("link")
    # ### end Alembic commands ###
