name: Run tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create env file
        run: cp .env.template .env
      - name: docker-compose up and run tests
        run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from tests